version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/var/www/html
        depends_on:
            - php
    php:
        container_name: php
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/var/www/html
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root-password
            MYSQL_DATABASE: website
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data: