version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/var/www/html
        depends_on:
            - php
    php:
        container_name: php
        image: php:8.2-fpm
        volumes:
            - ./app:/var/www/html